# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoeJackCity' do
  pod 'Stripe', '~> 14.0.0'
  inherit! :search_paths
  pod 'ReactNativePayments', :path => '../node_modules/react-native-payments'

end
